schema_version: 1

context:
  version: "0.7.3"
  python_min: "3.10"

package:
  name: solvax
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/solvax/solvax-${{ version }}.tar.gz
  sha256: a484001c1559393019ecc94837168f7bbef2795f9193549c5a062446374b1e09

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - jax
    - equinox

tests:
  - python:
      imports:
        - solvax
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Differentiable structured linear solvers, preconditioners and matrix-free methods in JAX
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/uwplasma/SOLVAX
  repository: https://github.com/uwplasma/SOLVAX
  documentation: https://solvax.readthedocs.io

extra:
  recipe-maintainers:
    - rogeriojorge
    - matthewfeickert
